name: Build and Deploy Locally

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Run Docker Container
        run: |
          cd /home/ubuntu/python/app || mkdir -p /home/ubuntu/python/app && cd /home/ubuntu/python/app
          git pull origin main || git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git .
          docker stop python-app || true
          docker rm python-app || true
          docker build -t python-app .
          docker run -d --name python-app -p 5000:5000 python-app
