name: Build and Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Connect to Server and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app || mkdir ~/app && cd ~/app
            git pull origin main || git clone https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO_NAME.git ~/app
            docker stop python-app || true
            docker rm python-app || true
            docker build -t python-app .
            docker run -d --name python-app -p 5000:5000 python-app
